
on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Pipeline run
        uses: ./
        id: greeting
        with:
          name: Wes

      - name: Greetings
        run: echo "${{ steps.greeting.outputs.greetings }}"